create table if not exists public.cases (
  id text primary key,
  title text not null,
  product text not null,
  category text,
  difficulty text,
  profile text,
  status text default 'ativo',
  modes jsonb default '[]'::jsonb,
  tags jsonb default '[]'::jsonb,
  message text,
  history jsonb default '[]'::jsonb,
  goal text,
  ideal text,
  criteria text,
  hint text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.results (
  id text primary key,
  seller_name text not null,
  seller_team text,
  mode text,
  average integer,
  xp integer,
  solved integer,
  cases jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  action text,
  title text,
  actor text,
  data jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  message text,
  created_at timestamptz default now()
);

alter table public.cases enable row level security;
alter table public.results enable row level security;
alter table public.audit_logs enable row level security;
alter table public.notifications enable row level security;

-- O backend usa SERVICE_ROLE_KEY, então não é necessário criar políticas públicas.

-- V31: métricas de satisfação e feedback final da sessão
alter table public.results add column if not exists csat_average numeric(3,2);
alter table public.results add column if not exists csat_count integer default 0;
alter table public.results add column if not exists supervisor_feedback text;
